apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-9597"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-9597"
  template:
    metadata:
      labels:
        app: "aksdemo-9597"
    spec:
      containers:
        - name: "aksdemo-9597"
          image: "aksdemogirn.azurecr.io/aksdemo"
          ports:
          - containerPort: 8080