on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksdemogirn.azurecr.io
        username: ${{ secrets.acr_aksdemogirn_username }}
        password: ${{ secrets.acr_aksdemogirn_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/testdemo" -f  "skaffold.yml" -t aksdemogirn.azurecr.io/aksdemo:${{ github.sha }} --label dockerfile-path=skaffold.yml
        docker push aksdemogirn.azurecr.io/aksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks_demob304 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks_demob304`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks_demob304
        container-registry-url: aksdemogirn.azurecr.io
        container-registry-username: ${{ secrets.acr_aksdemogirn_username }}
        container-registry-password: ${{ secrets.acr_aksdemogirn_password }}
        secret-name: aksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks_demob304
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksdemogirn.azurecr.io/aksdemo:${{ github.sha }}
        imagepullsecrets: |
          aksdemodockerauth
